// Code generated by "stringer -type InterpretAs"; DO NOT EDIT.

package interpreter2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InterpretAsUint8-0]
	_ = x[InterpretAsUint16-1]
	_ = x[InterpretAsUint32-2]
	_ = x[InterpretAsUint64-3]
	_ = x[InterpretAsFloat32-4]
	_ = x[InterpretAsFloat64-5]
	_ = x[InterpretAsCompressed-6]
}

const _InterpretAs_name = "InterpretAsUint8InterpretAsUint16InterpretAsUint32InterpretAsUint64InterpretAsFloat32InterpretAsFloat64InterpretAsCompressed"

var _InterpretAs_index = [...]uint8{0, 16, 33, 50, 67, 85, 103, 124}

func (i InterpretAs) String() string {
	if i < 0 || i >= InterpretAs(len(_InterpretAs_index)-1) {
		return "InterpretAs(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterpretAs_name[_InterpretAs_index[i]:_InterpretAs_index[i+1]]
}
